'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class index

    '''<summary>
    '''usrForm1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrForm1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''currentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currentDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents content As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''livedata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents livedata As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''orderMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents orderMetrics As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''todayDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents todayDate2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dbFeedback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dbFeedback As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
